### ISSUE TITLE
Theres no download in releases or packages!!

### ISSUE THREAD

**Issue by Llaughs** [tzvetkoff/mari0_se#1]
(A repository should have releases and/or packages)

**Comment by tzvetkoff** [comment]
Hi!

Thanks for the interest on the project.

I kinda forgot about this one right when I just imported it ~7 years ago.
I spent some time these days to show Mari0 some long deserved LÖVE and it now works (almost) as expected on LÖVE 11.4, plus I fixed other issues like the notoriously broken world `5-3`.

As this is derivative work to the original Mari0: SE b9 I still don't know if I'd ever provide official binaries -- there are still some things to be fixed, plus I still haven't decided whether to keep the effort of bringing more features.

For the time being, I'd suggest taking a look at a more maintained community fork -- https://github.com/Mari0-CE/Mari0-Community-Edition.
Unfortunately, Mari0-CE also needs some work to be done in order to function properly -- world `5-3` is still broken there, green flying Koopas fireball reaction is wrong, etc.

P.S. I've created a [release](https://github.com/tzvetkoff/mari0_se/releases/tag/0.0.19) so binaries are available, even though a lot of things might be broken.
HF.
